---
- name: Iniciar campaña
  hosts: controller
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yml"
  tasks:
    - name: Leer token de GoPhish desde .env si no está en env
      ansible.builtin.shell: |
        set -a
        source {{ project_root }}/.env
        echo $GOPHISH_API_KEY
      register: api_key
      changed_when: false

    - name: Construir payload (grupos por depto y región)
      ansible.builtin.script: build_groups.py {{ employees_csv }}
      args:
        chdir: "{{ project_root }}"
      register: groups_json

    - name: Crear/actualizar grupos en GoPhish
      ansible.builtin.uri:
        url: "http://localhost:3333/api/groups/"
        method: POST
        headers:
          Authorization: "Bearer {{ api_key.stdout | trim }}"
          Content-Type: application/json
        body_format: json
        body: "{{ item }}"
        status_code: [200, 201]
      loop: "{{ groups_json.stdout | from_json }}"

    - name: Crear campaña
      ansible.builtin.uri:
        url: "http://localhost:3333/api/campaigns/"
        method: POST
        headers:
          Authorization: "Bearer {{ api_key.stdout | trim }}"
          Content-Type: application/json
        body_format: json
        body: |
          {
            "name": "{{ campaign_defaults.name_prefix }} - {{ lookup('pipe','date +%Y-%m-%d_%H-%M') }}",
            "template": "{{ campaign_defaults.email_template_name }}",
            "page": "{{ campaign_defaults.landing_page_name }}",
            "url": "{{ campaign_defaults.url }}",
            "smtp": "{{ campaign_defaults.smtp_name }}",
            "groups": ["MX_All", "US_All"],
            "launch_date": "{{ campaign_defaults.launch_date }}"
          }
        status_code: [200, 201]
      register: new_campaign

    - name: Guardar ID de campaña creada en archivo local (para UI)
      ansible.builtin.copy:
        dest: "{{ project_root }}/.last_campaign_id"
        content: "{{ (new_campaign.json.id | default(new_campaign.json.data.id)) | string }}\n"
